import type { AutomationRule, Device, SummaryCard } from "./types";

export const summaryCards: SummaryCard[] = [
  {
    detail: "Solar is covering most current demand",
    icon: "🏡",
    title: "Home status",
    tone: "good",
    value: "Stable",
  },
  {
    detail: "3.8 kW solar, 0.4 kW import, 1.1 kW battery charge",
    icon: "⚡",
    title: "Utility power",
    tone: "info",
    value: "Using solar",
  },
  {
    detail: "Nest is idle, Tuya TRVs are following schedules",
    icon: "🌡️",
    title: "Heating",
    tone: "good",
    value: "Comfort",
  },
  {
    detail: "AJAX monitoring mode active",
    icon: "🛡️",
    title: "Security",
    tone: "warning",
    value: "Armed night",
  },
];

export const devices: Device[] = [
  {
    canControl: false,
    category: "solar",
    id: "esolar-aio3",
    integration: "eSolar AIO3",
    lastSeen: "Just now",
    metrics: [
      { label: "Solar", value: "3.8 kW" },
      { label: "House load", value: "2.3 kW" },
      { label: "Battery", value: "74%" },
      { label: "Grid", value: "0.4 kW import" },
    ],
    name: "eSolar AIO3 inverter",
    riskLevel: "medium",
    room: "Utility",
    status: "online",
  },
  {
    canControl: true,
    category: "heating",
    id: "nest-thermostat",
    integration: "Google Nest",
    lastSeen: "2 min ago",
    metrics: [
      { label: "Current", value: "20.5 C" },
      { label: "Target", value: "19.0 C" },
      { label: "Boiler", value: "Off" },
    ],
    name: "Nest thermostat",
    riskLevel: "medium",
    room: "Hall",
    status: "online",
  },
  {
    canControl: true,
    category: "radiator",
    id: "living-room-trv",
    integration: "Tuya TRV604",
    lastSeen: "1 min ago",
    metrics: [
      { label: "Room", value: "20.1 C" },
      { label: "Target", value: "19.5 C" },
      { label: "Battery", value: "82%" },
    ],
    name: "Living room radiator valve",
    riskLevel: "low",
    room: "Living room",
    status: "online",
  },
  {
    canControl: true,
    category: "lighting",
    id: "kitchen-light",
    integration: "Tuya",
    lastSeen: "Just now",
    metrics: [
      { label: "State", value: "On" },
      { label: "Brightness", value: "80%" },
    ],
    name: "Kitchen lights",
    riskLevel: "low",
    room: "Kitchen",
    status: "online",
  },
  {
    canControl: true,
    category: "lighting",
    id: "living-room-lamps",
    integration: "Sonoff",
    lastSeen: "Just now",
    metrics: [
      { label: "State", value: "Off" },
      { label: "Brightness", value: "0%" },
    ],
    name: "Living room lamps",
    riskLevel: "low",
    room: "Living room",
    status: "online",
  },
  {
    canControl: true,
    category: "socket",
    id: "washer-socket",
    integration: "Sonoff",
    lastSeen: "5 min ago",
    metrics: [
      { label: "State", value: "Off" },
      { label: "Power", value: "0 W" },
    ],
    name: "Washing machine socket",
    riskLevel: "medium",
    room: "Utility",
    status: "online",
  },
  {
    canControl: true,
    category: "socket",
    id: "desk-socket",
    integration: "Tuya",
    lastSeen: "Just now",
    metrics: [
      { label: "State", value: "On" },
      { label: "Power", value: "42 W" },
    ],
    name: "Desk socket",
    riskLevel: "low",
    room: "Office",
    status: "online",
  },
  {
    canControl: true,
    category: "water",
    id: "immersion-smart-mcb",
    integration: "Anttory WiFi smart MCB",
    lastSeen: "Just now",
    metrics: [
      { label: "State", value: "Off" },
      { label: "Cylinder", value: "54 C" },
      { label: "Power", value: "0 W" },
    ],
    name: "Anttory immersion MCB",
    riskLevel: "medium",
    room: "Hot water",
    status: "online",
  },
  {
    canControl: false,
    category: "security",
    id: "ajax-hub",
    integration: "AJAX",
    lastSeen: "Just now",
    metrics: [
      { label: "Mode", value: "Night armed" },
      { label: "Events", value: "No alarms" },
    ],
    name: "AJAX alarm hub",
    riskLevel: "security",
    room: "Hall",
    status: "warning",
  },
];

export const automationRules: AutomationRule[] = [
  {
    description: "Close selected TRV604 valves when the boiler is heating hot water only.",
    enabled: true,
    id: "summer-hot-water-trv",
    lastRun: "Today 07:10",
    name: "Summer hot-water valve close",
    recommendationOnly: false,
  },
  {
    description: "Suggest hot water boost when solar export stays high.",
    enabled: false,
    id: "solar-hot-water",
    lastRun: "Never",
    name: "Solar export to hot water",
    recommendationOnly: true,
  },
  {
    description: "Turn off selected lights and sockets when AJAX is armed.",
    enabled: false,
    id: "alarm-away-shutdown",
    lastRun: "Never",
    name: "Alarm armed shutdown",
    recommendationOnly: true,
  },
];

export function getDevicesByCategory(category: Device["category"]) {
  return devices.filter((device) => device.category === category);
}
